apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.credentialsSecretName" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZULIP_EMAIL: {{ .Values.zulip.email | quote }}
  ZULIP_API_KEY: {{ .Values.zulip.apiKey | quote }}
