name: 'Build docker image'
on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - "deploy/charts/**/*"      
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami/charts
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: hoprassociation
          install_components: beta                    
      - name: Check if docker tag exists
        run: |
          docker_tag=$(jq -r '.version' package.json)
          echo "Docker tag: ${docker_tag}"
          images=$(gcloud container images  list-tags  gcr.io/hoprassociation/network-service --filter="tags[]=${docker_tag}")
          echo "gcr images: ${images}"
          if [ "${images}" ne "Listed 0 items." ]; then 
            echo "The docker image tag already exists. Please bump package.json version"; 
            exit 1
          fi
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: hoprassociation/notification-service:latest
          build-args: |
            NODEJS_18_SHA='@sha256:2771803756cf54d0b8031fa5239420386608bcff9f69f9e8a7afda0671982537'
            NODEJS_18_ALPINE_SHA='@sha256:67373bd5d90ea600cb5f0fa58d7a5a4e6ebf50b6e05c50c1d1cc22df5134db43'
