name: 'Publish helm chart'
on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
    paths:
      - "deploy/charts/**/*"
defaults:
  run:
    working-directory: 'deploy/charts'
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Helm chart version
        run: |
          helm_chart_version=$(grep '^version:' deploy/charts/Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=helm-${helm_chart_version}" >> $GITHUB_ENV
      - name: Tag Helm version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag ${{ env.HELM_CHART_VERSION }}
            git push origin ${{ env.HELM_CHART_VERSION }}
