---

name: 'Publish Container'

on:
  push:
    branches:
      - master
    paths-ignore:
      - "charts/**/*"
concurrency:
  group: ${{ github.head_ref }}-container
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          install_components: beta

      - name: Google Container authentication
        run: gcloud auth configure-docker --quiet gcr.io

      - name: Get package version
        run: |
          docker_tag=$(jq -r '.version' package.json)
          echo "DOCKER_TAG=${docker_tag}" >> $GITHUB_ENV

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            gcr.io/hoprassociation/notification-service:${{ env.DOCKER_TAG }}
            gcr.io/hoprassociation/notification-service:latest
          build-args: |
            NODEJS_18_IMAGE=node:18@sha256:2771803756cf54d0b8031fa5239420386608bcff9f69f9e8a7afda0671982537
            NODEJS_18_ALPINE_IMAGE=node:18-alpine@sha256:67373bd5d90ea600cb5f0fa58d7a5a4e6ebf50b6e05c50c1d1cc22df5134db43
      - name: Tag Docker version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag ${{ env.DOCKER_TAG }}
            git push origin ${{ env.DOCKER_TAG }}
